


# load packages

```{r}
library(tidyverse)
library(ggpubr)
```

# load data
```{r}
path <- "FISH_EB/data/"

imageNames <- list.files("FISH_EB/Images")
#imageName <- "20250425-Cer1546-Lefty1488-GATA6cy5-(-AMPc+50ngActA)-03.czi" #add -1 if you use the line "Make Substack"

all_fish <- data.frame()

for (i in imageNames) {
pre_channel <- read.csv(paste0(path, i, "_C1.txt"), sep="\t", h = T) |> filter(Area >= 0.1) |> mutate(ImageName = i)
fish1 <- read.csv(paste0(path, i,"_C2.txt"), sep="\t", h = T) |> filter(Area >= 0.1) |> mutate(ImageName = i)
fish2 <- read.csv(paste0(path, i,"_C3.txt"), sep="\t", h = T) |> filter(Area >= 0.1) |> mutate(ImageName = i)
dapi  <- read.csv(paste0(path, i,"_C4.txt"), sep="\t", h = T) |> filter(Area >= 0.1) |> mutate(ImageName = i)

Ycenter <- mean(dapi$Y)
Xcenter <- mean(dapi$X)

pre_channel$distance <- sqrt((pre_channel$X - Xcenter)^2 + (pre_channel$Y - Ycenter)^2)
fish1$distance <- sqrt((fish1$X - Xcenter)^2 + (fish1$Y - Ycenter)^2)
fish2$distance <- sqrt((fish2$X - Xcenter)^2 + (fish2$Y - Ycenter)^2)

pre_channel$Origin <- "Pre-Channel"
fish1$Origin <- "Fish1"
fish2$Origin <- "Fish2"

all_fish <- rbind.data.frame(all_fish, pre_channel, fish1, fish2)

}
head(pre_channel)
summary(dapi$Y)
```


# plot
```{r}
library(patchwork)


p1 <- gghistogram(all_fish |> filter(!(Origin == "Pre-Channel")), 
    x = "distance", 
    color = "Origin", 
    fill = "Origin", 
    facet.by = "ImageName", 
    facet.wrap = TRUE, 
    ncol = length(unique(all_fish$ImageName)), 
    add_density = TRUE, 
    bins = 100)

p2 <- gghistogram(all_fish |> filter(Origin == "Pre-Channel"), 
    x = "distance", 
    color = "Origin", 
    fill = "Origin", 
    facet.by = "ImageName", 
    facet.wrap = TRUE, 
    ncol = length(unique(all_fish$ImageName)), 
    add_density = TRUE, 
    bins = 100)

p2 / p1
ggsave("FISH_EB/Images/all_fish_hist.png", width = 24, height = 12)

```